app_deployment:
  appName: expense-tracker-api
  image: nexus-docker-craigmiller160.ddns.net/expense-tracker-api:latest
  configMap:
    spring.profiles.active: prod
    spring.datasource.host: postgres.infra-prod
    spring.datasource.port: "5432"
    spring.datasource.db_name: expense_tracker_prod
    spring.flyway.locations: classpath:db/migration,classpath:db/prod/migration
    keycloak.realm: apps-prod
    keycloak.auth-server-url: https://keycloak.infra-prod:8443
    # This is safe because keycloak lives inside the cluster
    keycloak.disable-trust-manager: "true"
  onepassworditems:
    - name: expense-tracker-api-oauth2-keys
      itemPath: vaults/Home Server (Prod)/items/Expense Tracker API OAuth2 Keys
    - name: expense-tracker-postgres
      itemPath: vaults/Home Server (Prod)/items/Postgres Root Account
  ports:
    - containerPort: 8080
  secrets:
    - envVariable: spring.datasource.username
      secretName: expense-tracker-postgres
      secretKey: username
    - envVariable: spring.datasource.password
      secretName: expense-tracker-postgres
      secretKey: password
    - envVariable: keycloak.resource
      secretName: expense-tracker-api-oauth2-keys
      secretKey: kcClientId
    - envVariable: keycloak.credentials.secret
      secretName: expense-tracker-api-oauth2-keys
      secretKey: kcClientSecret
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTPS