app_deployment:
  appName: expense-tracker-api
  image: nexus-docker-craigmiller160.ddns.net/expense-tracker-api:latest
  configMap:
    spring.profiles.active: prod
    spring.datasource.host: postgres.infra-prod
    spring.datasource.port: "5432"
    oauth2.auth-server-host: https://sso-oauth2-server:8443
    oauth2.client-name: expense-tracker-api
    spring.datasource.db_name: expense_tracker_prod
    spring.flyway.locations: classpath:db/migration,classpath:db/prod/migration
  onepassworditems:
    - name: expense-tracker-api-oauth2-keys
      itemPath: vaults/Home Server (Prod)/items/Expense Tracker API OAuth2 Keys
    - name: expense-tracker-postgres
      itemPath: vaults/Home Server (Prod)/items/Postgres Root Account
  ports:
    - containerPort: 8080
  secrets:
    - envVariable: spring.datasource.username
      secretName: expense-tracker-postgres
      secretKey: username
    - envVariable: spring.datasource.password
      secretName: expense-tracker-postgres
      secretKey: password
    - envVariable: oauth2.client-key
      secretName: expense-tracker-api-oauth2-keys
      secretKey: clientKey
    - envVariable: oauth2.client-secret
      secretName: expense-tracker-api-oauth2-keys
      secretKey: clientSecret
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTPS