version: '3.5'

services:
  postgres:
    image: postgres:14.5
    container_name: expense_tracker_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: expense_tracker_keycloak
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_PASSWORD=password
      - KC_DB_USERNAME=postgres
      - KC_DB_URL=jdbc:postgresql://expense_tracker_postgres:5432/keycloak
    volumes:
      - ./src/test/resources:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres