apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-tracker-api-config
data:
  spring.profiles.active: prod
  spring.datasource.host: postgres.infra-prod
  spring.datasource.port: "5432"
  oauth2.auth-server-host: https://sso-oauth2-server:8443
  oauth2.client-name: expense-tracker-api
