spring:
  flyway:
    locations: classpath:db/migration,classpath:db/dev/migration

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    # TODO restore old log setting
    org.keycloak: TRACE