server:
  servlet:
    session:
      cookie:
        name: EXPENSE-TRACKER-SESSIONID
        path: /expense-tracker
  ssl:
    key-store-type: PKCS12
    key-store: classpath:expense-tracker.p12
    key-store-password: auth-manage-pass
    use-ssl: true
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-CHACHA20-POLY1305,ECDHE-RSA-CHACHA20-POLY1305,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDHE-ECDSA-AES128-SHA256,ECDHE-RSA-AES128-SHA256

spring:
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    host: craigmiller160.ddns.net
    port: "30019"
    db_name: "expense_tracker_dev"
    username: postgres_root
    password: ${POSTGRES_ROOT_PASSWORD}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db_name}
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

keycloak:
  realm: apps-dev
  auth-server-url: https://auth-craigmiller160.ddns.net
  ssl-required: external
  resource: expense-tracker-api
  use-resource-role-mappings: true
  credentials:
    secret: CQ60kzXcV7F31JfW8dX2MINjVIKOIxpJ

logging:
  level:
    io.craigmiller160.expensetrackerapi: DEBUG
    io.craigmiller160.webutils: DEBUG
    io.craigmiller160.oauth2: DEBUG