CREATE
    TABLE
        transaction_duplicates(
            id UUID NOT NULL,
            new_transaction_id UUID NOT NULL,
            possible_duplicate_transaction_id UUID NOT NULL,
            PRIMARY KEY(id),
            FOREIGN KEY(new_transaction_id) REFERENCES transactions(id),
            FOREIGN KEY(possible_duplicate_transaction_id) REFERENCES transactions(id)
        );

ALTER TABLE
    transactions ADD COLUMN content_hash BYTEA;

-- TODO when retrieving a transaction, make the duplicate flag be generated by a query to the duplicates table for matches
ALTER TABLE
    transactions DROP
        COLUMN duplicate;

UPDATE
    transactions
SET
    content_hash = SHA256(
        CONCAT(
            expense_date,
            amount,
            description
        )
    );

ALTER TABLE
    transactions ALTER COLUMN content_hash
SET
    NOT NULL;